"""
Master list of study sites. Keys are USGS site IDs; values hold metadata.
Add additional sites as needed following the same schema.
"""

MASTER_STUDY_SITES = {
    "03479000": {
        "name": "Watauga River near Sugar Grove, NC",
        "full_name": "Watauga River near Sugar Grove, NC",
        "state": "NC",
        "biome": "Appalachian mixed forest",
        "lat": 36.239167,
        "lon": -81.822222,
        "watershed": "Watauga River (HUC 06010103)",
        "nwm_comid": 19743430,
        "usgs_id": "03479000",
        "regulated_flag": False,
        "regulation_status": "Unregulated",
        "upstream_of": ["03486000"],
        "data_sources": ["ERA5", "NWM", "USGS"],
    },
    "03486000": {
        "name": "Watauga River at Elizabethton, TN",
        "full_name": "Watauga River at Elizabethton, TN",
        "state": "TN",
        "biome": "Appalachian mixed forest",
        "lat": 36.355919,
        "lon": -82.223547,
        "watershed": "Watauga River (downstream, regulated)",
        "nwm_comid": 19745222,
        "usgs_id": "03486000",
        "regulated_flag": True,
        "regulation_status": "Regulated",
        "upstream_of": [],
        "data_sources": ["ERA5", "NWM", "USGS"],
    },
    "03161000": {
        "name": "South Fork New River near Jefferson, NC",
        "full_name": "South Fork New River near Jefferson, NC",
        "state": "NC",
        "biome": "Appalachian mixed forest",
        "lat": 36.393333,
        "lon": -81.406944,
        "watershed": "South Fork New River (HUC 05050001)",
        "nwm_comid": 6892192,
        "usgs_id": "03161000",
        "regulated_flag": False,
        "regulation_status": "Unregulated",
        "upstream_of": ["03164000"],
        "data_sources": ["ERA5", "NWM", "USGS"],
    },
    "03164000": {
        "name": "New River near Galax, VA",
        "full_name": "New River near Galax, VA",
        "state": "VA",
        "biome": "Appalachian mixed forest",
        "lat": 36.64735,
        "lon": -80.978969,
        "watershed": "New River mainstem (downstream integrator)",
        "nwm_comid": 6887572,
        "usgs_id": "03164000",
        "regulated_flag": False,
        "regulation_status": "Unregulated",
        "upstream_of": [],
        "data_sources": ["ERA5", "NWM", "USGS"],
    },
}
